### PR TITLE
changed the func images

### PR DESCRIPTION
**Pull request by willweatherman**

### CODE REVIEW

**Comment by giftedprimate** [comment]
@willweatherman Also replace index `55` and index `91` as well please. Thanks.

**Comment by willweatherman** [comment]
ok give me 10 minuets.

**Comment by giftedprimate** [comment]
Thanks man!

**Comment by willweatherman** [comment]
Hey it seams that after pushing my changes to my origin more-images the jw mathbot got the same changes can you confirm that index 55 and 91 are no longer playing cards?

**Pull request merged**
